# Generated by Django 4.1.2 on 2022-10-30 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_document_sha_256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
