# Generated by Django 4.1.2 on 2022-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0003_alter_document_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signed_by_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_by_insurance_firm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_by_pharmacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_by_professional',
            field=models.BooleanField(default=False),
        ),
    ]
