# Generated by Django 4.1.2 on 2022-10-25 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Hospital'), ('2', 'Pharmacy'), ('3', 'Insurance')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('images', models.TextField()),
                ('location', models.TextField()),
                ('licenses', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('permits', models.FileField(blank=True, null=True, upload_to='permits/')),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Patient'), ('2', 'Professional')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('proof_of_id', models.FileField(upload_to='proof_of_id/')),
                ('proof_of_address', models.FileField(upload_to='proof_of_address/')),
                ('health_license', models.FileField(blank=True, null=True, upload_to='health_license/')),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
        ),
    ]
