# Generated by Django 4.1.2 on 2022-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_organization_name_remove_personaluser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='HOTP_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='HOTP_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
