# Generated by Django 4.1.2 on 2022-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0007_rename_proof_of_id_personaluser_proof_of_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
