# Generated by Django 4.1.2 on 2022-11-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_proof_of_id_personaluser_proof_of_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
