# Generated by Django 4.1.2 on 2022-11-28 15:39

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0009_customuser_upload_till_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
