# Generated by Django 4.1.2 on 2022-11-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_orderitem_alter_order_status_delete_orderentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices'),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
