# Generated by Django 4.1.2 on 2022-11-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0008_customuser_two_factor_enabled'),
        ('products', '0005_order_prescription_alter_order_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status',
                 models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Rejected')], default='1',
                                  max_length=2)),
                ('order',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claim',
                                      to='products.order')),
                ('provider',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims',
                                   to='authentication.organization')),
            ],
        ),
    ]
